import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PrismicPreview } from '@prismicio/next'
import { repositoryName } from '@/prismicio'

import './globals.css'
import Header from '@/components/layout/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en-gb">
      <body className={inter.className}>
        <Header />
        {children}
        {/* preview */}
        <PrismicPreview repositoryName={repositoryName} />
      </body>
    </html>
  )
}
